extends: "airbnb"
env:
  browser: true
  es6: true
  jquery: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  object-curly-spacing: [warn, never]
  react/jsx-filename-extension: [error, { "extensions": [".js", ".jsx"] }]
